// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetStatus():Promise<Record<string, any>>;

export function HideWindow():Promise<void>;

export function OpenLogFile():Promise<void>;

export function Quit():Promise<void>;

export function ShowWindow():Promise<void>;
